#
# Kimengumi Command Line Interface Environnement (kclie)
#
# Licensed under the EUPL, Version 1.2 or – as soon they will be approved by
# the European Commission - subsequent versions of the EUPL (the "Licence");
# You may not use this work except in compliance with the Licence.
# You may obtain a copy of the Licence at:
#
# https://joinup.ec.europa.eu/software/page/eupl
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the Licence is distributed on an "AS IS" basis,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the Licence for the specific language governing permissions and
# limitations under the Licence.
#
# @author Antonio Rossetti <antonio@rossetti.fr>
# @copyright since 2009 Antonio Rossetti
# @license <https://joinup.ec.europa.eu/software/page/eupl> EUPL
#

services:

    kclie-debian-oldoldstable:
        container_name: kclie-debian-oldoldstable
        image: debian:oldoldstable
        pull_policy: always
        stdin_open: true
        tty: true
        volumes:
            -   type: bind
                source: ./
                target: /opt/kclie
            - debian-oldoldstable-var-cache-apt:/var/cache/apt
            - debian-oldoldstable-var-lib-apt:/var/lib/apt
        command: bash -c ". /opt/kclie/docker-entrypoint.sh"

    kclie-debian-oldstable:
        container_name: kclie-debian-oldstable
        image: debian:oldstable
        pull_policy: always
        stdin_open: true
        tty: true
        volumes:
            -   type: bind
                source: ./
                target: /opt/kclie
            - debian-oldstable-var-cache-apt:/var/cache/apt
            - debian-oldstable-var-lib-apt:/var/lib/apt
        command: bash -c ". /opt/kclie/docker-entrypoint.sh"

    kclie-debian-stable:
        container_name: kclie-debian
        image: debian:stable
        pull_policy: always
        stdin_open: true
        tty: true
        volumes:
            -   type: bind
                source: ./
                target: /opt/kclie
            - debian-stable-var-cache-apt:/var/cache/apt
            - debian-stable-var-lib-apt:/var/lib/apt
        command: bash -c ". /opt/kclie/docker-entrypoint.sh"

    kclie-debian-testing:
        container_name: kclie-debian
        image: debian:testing
        pull_policy: always
        stdin_open: true
        tty: true
        volumes:
            -   type: bind
                source: ./
                target: /opt/kclie
            - debian-testing-var-cache-apt:/var/cache/apt
            - debian-testing-var-lib-apt:/var/lib/apt
        command: bash -c ". /opt/kclie/docker-entrypoint.sh"

    kclie-ubuntu-latest:
        container_name: kclie-ubuntu
        image: ubuntu:latest
        pull_policy: always
        stdin_open: true
        tty: true
        volumes:
            -   type: bind
                source: ./
                target: /opt/kclie
            - ubuntu-latest-var-cache-apt:/var/cache/apt
            - ubuntu-latest-var-lib-apt:/var/lib/apt
        command: bash -c ". /opt/kclie/docker-entrypoint.sh"

    kclie-ubuntu-rolling:
        container_name: kclie-ubuntu
        image: ubuntu:rolling
        pull_policy: always
        stdin_open: true
        tty: true
        volumes:
            -   type: bind
                source: ./
                target: /opt/kclie
            - ubuntu-rolling-var-cache-apt:/var/cache/apt
            - ubuntu-rolling-var-lib-apt:/var/lib/apt
        command: bash -c ". /opt/kclie/docker-entrypoint.sh"

    kclie-ubuntu-devel:
        container_name: kclie-ubuntu
        image: ubuntu:devel
        pull_policy: always
        stdin_open: true
        tty: true
        volumes:
            -   type: bind
                source: ./
                target: /opt/kclie
            - ubuntu-devel-var-cache-apt:/var/cache/apt
            - ubuntu-devel-var-lib-apt:/var/lib/apt
        command: bash -c ". /opt/kclie/docker-entrypoint.sh"
volumes:
    debian-oldoldstable-var-cache-apt:
    debian-oldoldstable-var-lib-apt:
    debian-oldstable-var-cache-apt:
    debian-oldstable-var-lib-apt:
    debian-stable-var-cache-apt:
    debian-stable-var-lib-apt:
    debian-testing-var-cache-apt:
    debian-testing-var-lib-apt:
    ubuntu-devel-var-cache-apt:
    ubuntu-devel-var-lib-apt:
    ubuntu-latest-var-cache-apt:
    ubuntu-latest-var-lib-apt:
    ubuntu-rolling-var-cache-apt:
    ubuntu-rolling-var-lib-apt: