#!/bin/bash
#
# Kimengumi Command Line Interface Environnement
#
# Install a full generic Apache / multi Php-fpm dev stack using Ondrej PPA
#
# Copyright 2021 Antonio Rossetti (https://www.kimengumi.fr)
#
# Licensed under the EUPL, Version 1.1 or – as soon they will be approved by
# the European Commission - subsequent versions of the EUPL (the "Licence");
# You may not use this work except in compliance with the Licence.
# You may obtain a copy of the Licence at:
#
# https://joinup.ec.europa.eu/software/page/eupl
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the Licence is distributed on an "AS IS" basis,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the Licence for the specific language governing permissions and
# limitations under the Licence.

# Check KCLIE env and load if necessary
if [ "x${KCLIE_PATH}" = "x" ] ; then
	source `dirname $0`/../env
fi

if [ ! -x /usr/bin/add-apt-repository ] ; then
  echo 'Current version is for Ubuntu only'
  exit 1
fi

if [ "${SUDO_USER}x" = 'x' ] || [ "${SUDO_USER}x" = 'rootx' ] ; then
  echo 'This script is intented to be run in sudo from the dev user'
  exit 1
fi

add-apt-repository -y ppa:ondrej/php

apt-get install -y apache2 apache2-utils

echo -e "\n\t# APACHE CONFIG \n"

a2enmod rewrite
a2enmod headers
a2enmod ssl
a2enmod proxy_fcgi
a2enmod autoindex
a2enmod macro

a2dissite 000-default
a2dissite default-ssl

cp -r ${KCLIE_PATH}/etc/apache2/* /etc/apache2/

a2enconf kclie-dev-multi-fpm.conf
a2ensite 0000-kclie-dev-default.conf

chmod ugo+x /home/${SUDO_USER}
sudo -u ${SUDO_USER} mkdir -p /home/${SUDO_USER}/web/
echo '<?php phpinfo();' | sudo -u ${SUDO_USER} tee -a /home/${SUDO_USER}/web/phpinfo.php
chown ${SUDO_USER}:www-data /etc/apache2/sites-enabled

for VP in 5.6 7.0 7.1 7.2 7.3 7.4 8.0 8.1
do
  echo -e "\n\t# INSTALL PHP $VP\n"
  NP=`echo ${VP} | sed "s/\.//g"`
  apt-get install -y php${VP}-fpm php${VP}-bcmath php${VP}-bz2 php${VP}-curl php${VP}-gd php${VP}-intl php${VP}-mbstring php${VP}-mysql php${VP}-soap php${VP}-readline php${VP}-xml php${VP}-zip
  apt-get install -y php${VP}-mcrypt
  sed -i "s/user \= www-data/user \= ${SUDO_USER}/g" /etc/php/${VP}/fpm/pool.d/www.conf
  sed -i "s/pm.start_servers \= 2/pm.start_servers \= 1/g" /etc/php/${VP}/fpm/pool.d/www.conf
  systemctl restart php${VP}-fpm
  sudo -u ${SUDO_USER} echo "Use DevPhpFpmVhost ${VP} php${NP}.localhost /home/${SUDO_USER}/web/" > /etc/apache2/sites-enabled/php${NP}.localhost.conf
done

echo -e "\n\t# RESTART APACHE\n"

systemctl restart apache2
