#!/bin/bash
#
# Kimengumi Command Line Interface Environnement (kclie)
#
# Licensed under the EUPL, Version 1.2 or – as soon they will be approved by the European Commission - subsequent versions of the EUPL (the "Licence");
# You may not use this work except in compliance with the Licence.
# You may obtain a copy of the Licence at:  https://joinup.ec.europa.eu/software/page/eupl
#
# This work is provided under the Licence on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, express or implied.
#
# @author Antonio Rossetti <antonio@rossetti.fr>
# @copyright since 2009 Antonio Rossetti
# @license <https://joinup.ec.europa.eu/software/page/eupl> EUPL
#

#
# Create a user for a local mysql server with a wildcard database creation authorization based on username
#

echo

if [ "x$1" != "x" ]; then
    USER=$1
    echo "User login & database name : ${USER}"
else
    echo -e "User login & database name  :"
    read USER
fi

read -p "Do You want to generate a password ? [Y/n] : " GENPASS
if [ "x${GENPASS}" = "xn" ]; then
    echo -e "User password :"
    read PASS
else
    PASS=$($(dirname $0)/../bin/genpass)
    if [ "x${PASS}" = "x" ]; then
        echo 'Can not generate a password'
        exit 1
    fi
    echo "
        Password : ${PASS}
        "
fi

mysql -e "CREATE DATABASE \`${USER}\`"

for LOCALHOST in "127.0.0.1" "::1" "localhost"; do
    mysql -e "CREATE USER '${USER}'@'${LOCALHOST}' IDENTIFIED BY '${PASS}'" || exit 1
    mysql -e "GRANT USAGE ON * . * TO '${USER}'@'${LOCALHOST}'" || exit 1
    mysql -e "GRANT ALL PRIVILEGES ON \`${USER}\` . * TO '${USER}'@'${LOCALHOST}'" || exit 1
    mysql -e "GRANT TRIGGER ON \`${USER}\` . * TO '${USER}'@'${LOCALHOST}'"
done

echo "Account created"
