#!/bin/bash
#
# Kimengumi Command Line Interface Environnement
#
# Create a user for a local mysql server with a wildcard database creation
# authorization based on username
#
# Copyright 2017 Antonio Rossetti (https://www.kimengumi.fr)
#
# Licensed under the EUPL, Version 1.1 or – as soon they will be approved by
# the European Commission - subsequent versions of the EUPL (the "Licence");
# You may not use this work except in compliance with the Licence.
# You may obtain a copy of the Licence at:
#
# https://joinup.ec.europa.eu/software/page/eupl
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the Licence is distributed on an "AS IS" basis,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the Licence for the specific language governing permissions and
# limitations under the Licence.

echo

if [ "x$1" != "x" ] ; then
	USER=$1
	echo "User login : ${USER}"
else
	echo -e "User login :"
	read USER
fi

PASS=`genpass`

if [ "x${PASS}" = "x" ] ; then
	echo 'Can not generate a password'
	exit 1
fi

echo "
Password : '${PASS}
"

for LOCALHOST in "127.0.0.1" "::1" "localhost" ; do
	mysql -e "CREATE USER '${USER}'@'${LOCALHOST}' IDENTIFIED BY '${PASS}'" || exit 1
	mysql -e "GRANT USAGE ON * . * TO '${USER}'@'${LOCALHOST}' IDENTIFIED BY '${PASS}'" || exit 1
	mysql -e "GRANT ALL PRIVILEGES ON \`${USER}\_%\` . * TO '${USER}'@'${LOCALHOST}'" || exit 1
done

echo "Done

If you whish to allow autologin from cli, you can copy/paste the ~/.my.cnf sample file bellow, and write it in the final user homedir.

--------- ~/.my.cnf ---------
[client]
host     = localhost
user     = ${USER}
password = ${PASS}
-----------------------------"
