#!/bin/bash
#
# Kimengumi Command Line Interface Environnement
#
# Launch ps_mem with the lastest python available
# (#!/usr/bin/env python is not always available on lastest distribs)
#
# Copyright 2022 Antonio Rossetti (https://www.kimengumi.fr)
#
# Licensed under the EUPL, Version 1.1 or – as soon they will be approved by
# the European Commission - subsequent versions of the EUPL (the "Licence");
# You may not use this work except in compliance with the Licence.
# You may obtain a copy of the Licence at:
#
# https://joinup.ec.europa.eu/software/page/eupl
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the Licence is distributed on an "AS IS" basis,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the Licence for the specific language governing permissions and
# limitations under the Licence.

for PY in `which python3 python2 python` ; do
  if [ -x ${PY} ] ; then
    ${PY} ${KCLIE_PATH}/vendor/ps_mem/ps_mem.py "$@"
    exit 0
  fi
done
