#!/bin/bash
#
# Kimengumi Command Line Interface Environnement (kclie)
#
# Licensed under the EUPL, Version 1.2 or – as soon they will be approved by
# the European Commission - subsequent versions of the EUPL (the "Licence");
# You may not use this work except in compliance with the Licence.
# You may obtain a copy of the Licence at:
#
# https://joinup.ec.europa.eu/software/page/eupl
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the Licence is distributed on an "AS IS" basis,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the Licence for the specific language governing permissions and
# limitations under the Licence.
#
# @author Antonio Rossetti <antonio@rossetti.fr>
# @copyright since 2009 Antonio Rossetti
# @license <https://joinup.ec.europa.eu/software/page/eupl> EUPL
#

#
# Create a dump for each vhost created with wizard/vhost
#

if ! declare -F BatchEcho > /dev/null; then
    . "$(dirname ${BASH_SOURCE[0]:-$0})/../lib/batch.bash"
fi
if ! declare -F GetVhostVarsFromVhostDir > /dev/null; then
    . "$(dirname ${BASH_SOURCE[0]:-$0})/../lib/vhost.bash"
fi

mysql -Bse "FLUSH TABLES WITH READ LOCK;" 2>/dev/null && SKIP_LOCK_TABLES="--skip-lock-tables" && BatchEcho "Lock all tables of all databases"

REMAIN_DBS=($(mysql -Bse "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME NOT IN ('information_schema', 'mysql', 'performance_schema', 'sys');"))

# dump matching wizard/vhost DBs in the according vhost dir
for SEARCH in $(ls --color=never -d  /home/*/web/*/db.config.php); do

    VHOST_DIR=$(dirname ${SEARCH});
    GetVhostVarsFromVhostDir

    for REMAIN_DB_KEY in "${!REMAIN_DBS[@]}"; do
        if [ "${REMAIN_DBS[${REMAIN_DB_KEY}]}" == "${VHOST_DB_NAME}" ]; then

            BatchEcho Dump DB ${VHOST_DB_NAME} \> ${VHOST_DB_DUMP}
            mysqldump ${SKIP_LOCK_TABLES} -f ${VHOST_DB_NAME} | gzip -9f > ${VHOST_DB_DUMP}
            chmod 600 ${VHOST_DB_DUMP}
            chown ${VHOST_USER} ${VHOST_DB_DUMP}
            unset 'REMAIN_DBS[REMAIN_DB_KEY]'
        fi
    done
done

# dump remaining DBs in DEFAULT_BACKUP_DIR/mysql
for REMAIN_DB_KEY in "${!REMAIN_DBS[@]}"; do

    mkdir -p ${DEFAULT_BACKUP_DIR}/mysql

    DB_NAME=${REMAIN_DBS[${REMAIN_DB_KEY}]}
    DB_DUMP="${DEFAULT_BACKUP_DIR}/mysql/${DB_NAME}.sql.gz"
    BatchEcho Dump DB ${DB_NAME} \> ${DB_DUMP}
    mysqldump ${SKIP_LOCK_TABLES} -f ${DB_NAME} | gzip -9f > ${DB_DUMP}
    chmod 600 ${DB_DUMP}
    chown ${VHOST_USER} ${DB_DUMP}

done

if [ -n "${SKIP_LOCK_TABLES}" ]; then
    BatchEcho "Unlock tables"
    mysql -Bse "UNLOCK TABLES;"
fi