#!/bin/bash
#
# Kimengumi Command Line Interface Environnement (kclie)
#
# Licensed under the EUPL, Version 1.2 or – as soon they will be approved by
# the European Commission - subsequent versions of the EUPL (the "Licence");
# You may not use this work except in compliance with the Licence.
# You may obtain a copy of the Licence at:
#
# https://joinup.ec.europa.eu/software/page/eupl
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the Licence is distributed on an "AS IS" basis,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the Licence for the specific language governing permissions and
# limitations under the Licence.
#
# @author Antonio Rossetti <antonio@rossetti.fr>
# @copyright since 2009 Antonio Rossetti
# @license <https://joinup.ec.europa.eu/software/page/eupl> EUPL
#

#
# Install & update a standardized Apache / MariaDb / multi-Php DEV stack using Ondrej PPA
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !!! The kind of rules deployed by this wizard is for LOCAL DEVELOPMENT environment ONLY ! !!!
# !!! It is NOT SUITABLE FOR PRODUCTION environments !                                      !!!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

# Splashscreen
echo -e "\033[1;97;49m$(head -n 4 $0 | tail -n 3)\n#\twizard/$(basename "$0")\n$(head -n 29 $0 | tail -n 7)\033[0m\n"

# Check KCLIE env and load if necessary
if [ "x${KCLIE_PATH}" = "x" ]; then
    source $(dirname $0)/../env
fi

if [ "${SUDO_USER}x" = 'x' ] || [ "${SUDO_USER}x" = 'rootx' ]; then
    echo 'This script is intended to be run in sudo from the dev user'
    exit 1
fi

echo "# INSTALL STACK"
export DEBIAN_FRONTEND=noninteractive
${KCLIE_PATH}/sbin/apt-use-sury-php-packages

# Detect available PHPs from fpm packages
apt-cache --generate pkgnames >/tmp/pkgnames.list
PHPS=$(gawk -e 'match($0,/php([0-9]\.[0-9])-fpm/,r) {print r[1] }' /tmp/pkgnames.list | sort)

# Install all usual mods available for all PHPs available
rm -f /tmp/phpinstall.list 2> /dev/null
for VP in ${PHPS}; do
    for MOD in fpm bcmath bz2 curl gd imagick intl memcache memcached mbstring mcrypt mysql opcache redis readline soap xml zip; do
        echo php${VP}-${MOD} >>/tmp/phpinstall.list
    done
done

# filter to avoid install of nonexistent modules on certain php versions
grep -wFf /tmp/phpinstall.list /tmp/pkgnames.list | xargs apt install -qqy apache2 apache2-utils mariadb-server mariadb-client libnss3-tools mkcert

echo "# CONFIG APACHE"
# Apply kclie apache skeleton
cp -r ${KCLIE_PATH}/etc/apache2/* /etc/apache2/
PHPXX_CONF="/etc/apache2/sites-available/kclie-dev-multi-fpm.conf"
printf "\n\n# This file is auto-generated on each update on KCLIE dev-multi-fpm stack. Please do not modify\n\n" >${PHPXX_CONF}

a2dissite 000-default
a2dissite default-ssl
a2enmod rewrite
a2enmod headers
a2enmod ssl
a2enmod proxy_fcgi
a2enmod autoindex
a2enmod macro
a2enconf kclie-base.conf
a2enconf kclie-dev-multi-fpm.conf
a2ensite 0000-kclie-default.conf
a2ensite kclie-dev-multi-fpm.conf

# remove old global files from previous versions
for OLDCONF in 0000-kclie-dev-default 0010-kclie-dev-phpxx-localhost ; do
    if [ -e /etc/apache2/sites-available/${OLDCONF}.conf ] ; then
        rm -f /etc/apache2/sites-*/${OLDCONF}.conf
    fi
done

echo "# CONFIG SSL"
# SSL local cert
sudo -u ${SUDO_USER} mkcert -install
export CAROOT=/home/${SUDO_USER}/.local/share/mkcert
mkcert -cert-file /etc/ssl/certs/kclie-dev-multi-fpm.pem -key-file /etc/ssl/private/kclie-dev-multi-fpm.key '*.dev.localhost' '127.0.0.1' '::1'

if [ -e /usr/bin/ddev ] ; then
    echo -e "\n# CONFIG DDEV compatibility"
    a2enmod proxy_http
    a2ensite kclie-ddev.conf
    mkcert -cert-file /etc/ssl/certs/kclie-ddev.pem -key-file /etc/ssl/private/kclie-ddev.key '*.ddev.site' '127.0.0.1' '::1'
fi

echo "# CONFIG DIRS"
# Web root is in current user home
chmod ugo+x /home/${SUDO_USER}
sudo -u ${SUDO_USER} mkdir -p /home/${SUDO_USER}/web/
echo '<?php phpinfo();' >/home/${SUDO_USER}/web/phpinfo.php

# Allow current user to directly write custom vhost
chown ${SUDO_USER}:www-data /etc/apache2/sites-enabled

# Default vhost
if [ ! -e /var/www/html/index.html ] || grep -q 'Default Page: It works' /var/www/html/index.html ; then
    echo "<html></html>" > /var/www/html/index.html
fi
if [ ! -e /var/www/html/robots.txt ]; then
    echo -e "User-Agent: *\nDisallow: /" > /var/www/html/robots.txt
fi

# Config FPMs
echo "# CONFIG PHP"
for VP in ${PHPS}; do
    echo -n "$VP  "

    # in a local dev environment, php-fpm will run with the current user uid
    sed -i "s/user \= www-data/user \= ${SUDO_USER}/g" /etc/php/${VP}/fpm/pool.d/www.conf
    sed -i "s/pm.start_servers \= 2/pm.start_servers \= 1/g" /etc/php/${VP}/fpm/pool.d/www.conf

    # generated default phpXX.dev.localhost vhost foreach php version
    NP=$(echo ${VP} | sed "s/\.//g")
    echo "Use DevPhpVhost ${VP} php${NP} /home/${SUDO_USER}/web/" >>${PHPXX_CONF}
    # retro-compatibility for old style urls
    echo "Use DevPhpFpmVhost ${VP} php${NP}.localhost /home/${SUDO_USER}/web/" >>${PHPXX_CONF}

    # remove old files by php version from previous versions
    if [ -e /etc/apache2/sites-enabled/php${NP}.localhost.conf ] ; then
        rm -f /etc/apache2/sites-*/php${NP}.localhost.conf
    fi
done

echo "# CONFIG MARIADB"
# Allow usage of local Mariadb from docker
MBD_MAJ_VER=$(mysql -V | awk '{ print $5 }' | sed 's/,//' | awk -F. '{ print $2 }')
MBD_MIN_VER=$(mysql -V | awk '{ print $5 }' | sed 's/,//' | awk -F. '{ print $1 }')
if [[ "${MBD_MAJ_VER}" -lt 10 ]] || [[ "${MBD_MAJ_VER}" -eq 10 && "${MBD_MIN_VER}" -lt 11 ]]; then
    sed -i "s/bind-address *\= 127.0.0.1/bind-address \= 0.0.0.0/g" /etc/mysql/mariadb.conf.d/50-server.cnf
else
    sed -i "s/bind-address *\= 127.0.0.1/bind-address \= 172.17.0.1,127.0.0.1/g" /etc/mysql/mariadb.conf.d/50-server.cnf
fi

for LOCALHOST in "127.0.0.1" "::1" "localhost" "172.%"; do
    mysql -e "CREATE USER IF NOT EXISTS 'dev'@'${LOCALHOST}' IDENTIFIED BY 'dev'"
    mysql -e "GRANT USAGE ON * . * TO 'dev'@'${LOCALHOST}'"
    mysql -e "GRANT ALL PRIVILEGES ON \`dev\_%\` . * TO 'dev'@'${LOCALHOST}'"
    mysql -e "GRANT TRIGGER ON \`dev\_%\` . * TO 'dev'@'${LOCALHOST}'"
    # retro-compatibility of previous versions
    mysql -e "GRANT ALL PRIVILEGES ON \`git\_%\` . * TO 'dev'@'${LOCALHOST}'"
    mysql -e "GRANT TRIGGER ON \`git\_%\` . * TO 'dev'@'${LOCALHOST}'"
    mysql -e "GRANT ALL PRIVILEGES ON \`${SUDO_USER}\_%\` . * TO 'dev'@'${LOCALHOST}'"
    mysql -e "GRANT TRIGGER ON \`${SUDO_USER}\_%\` . * TO 'dev'@'${LOCALHOST}'"
done
mysql -e 'FLUSH PRIVILEGES'

echo "[client]
host     = localhost
user     = dev
password = dev" >/home/${SUDO_USER}/.my.cnf

echo "# RESTART STACK"
systemctl restart apache2 || service apache2 restart
systemctl restart mysql || service mariadb restart
for VP in ${PHPS}; do
    systemctl restart php${VP}-fpm || service php${VP}-fpm  restart
done

echo -e "\n#### HOW TO USE #######################\n"
rm /tmp/phpinstall.list /tmp/pkgnames.list

echo -e "Available default vhosts foreach php version are:"
COUNT=0
for VP in ${PHPS}; do
    echo -n "https://php$(echo ${VP} | sed "s/\.//g").dev.localhost  "
    COUNT=$((COUNT + 1))
    if [ $((COUNT % 3)) -eq 0 ]; then
        echo ""
    fi
done
echo "All pointing to : /home/${SUDO_USER}/web/

Your local Mysql/MariaDb user is :
$(cat /home/${SUDO_USER}/.my.cnf)
It can access/manage any database prefixed by : dev_*

Your can quickly declare custom dev vhost in with the following macro :
    Use DevPhpVhost x.y name /path/to/docroot

example for https://mywebsite.dev.localhost :
    /etc/apache2/sites-enabled/mywebsite.conf :
    Use DevPhpVhost 8.5 mywebsite /path/to/mywebsite
"