#
# Kimengumi Command Line Interface Environnement
#
# ZSH profile
#
# Copyright 2017 Antonio Rossetti (https://www.kimengumi.fr)
#
# Licensed under the EUPL, Version 1.1 or – as soon they will be approved by
# the European Commission - subsequent versions of the EUPL (the "Licence");
# You may not use this work except in compliance with the Licence.
# You may obtain a copy of the Licence at:
#
# https://joinup.ec.europa.eu/software/page/eupl
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the Licence is distributed on an "AS IS" basis,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the Licence for the specific language governing permissions and
# limitations under the Licence.

if [ ! -e ${HOME}/.zshrc ] ; then
	touch ${HOME}/.zshrc
fi

# ssh-agent (multiple ssh keys)
# Check if an agent is already running for the current user
export SSH_AGENT_PID="`pgrep -u ${USERNAME} ssh-agent | head -n1`"
if [ "x${SSH_AGENT_PID}" != "x" ] ; then
	# Retrive socket from PID
	# Linux
	if [ `(ls /tmp/ssh-*/agent.*.${SSH_AGENT_PID}) >/dev/null 2>&1` ] ; then
		for SOCK in `ls --color=never /tmp/ssh-*/agent.*.${SSH_AGENT_PID}` ; do
			export SSH_AUTH_SOCK="`cat ${SOCK}`"
		done
	fi
	# MacOs
        if [ `(ls /var/folders/*/*/*/ssh-*/agent.*.${SSH_AGENT_PID}) >/dev/null 2>&1` ] ; then
                for SOCK in `ls --color=never /var/folders/*/*/*/ssh-*/agent.*.${SSH_AGENT_PID}` ; do
                        export SSH_AUTH_SOCK="`cat ${SOCK}`"
                done
        fi
else
	# start ssh-agent
	eval `ssh-agent` >/dev/null
	# Leave a file allowing other terminals to retrive the agent
	echo ${SSH_AUTH_SOCK} > ${SSH_AUTH_SOCK}.${SSH_AGENT_PID}
fi

# history
export HISTSIZE=2000
export HISTFILE="${HOME}/.zshist_${USERNAME}_${SUDO_USER}"
export SAVEHIST=${HISTSIZE}
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt extendedglob

# If a local Oh My Zsh is detected, we use it
if [ -e $HOME/.oh-my-zsh/oh-my-zsh.sh ] ; then

	# No default configuration in this case.
	# All have to be done in the local user ~/.zshrc

# Else, if a shared installation is detected, we use it
elif [ -e ${KCLIE_PATH}/vendor/oh-my-zsh/oh-my-zsh.sh ] ; then

	#Basic Oh My Zsh configuration for shared installation
	export ZSH=${KCLIE_PATH}/vendor/oh-my-zsh/
	export ZSH_CACHE_DIR=${HOME}/.oh-my-zsh/cache
	if [ ! -w ${ZSH_CACHE_DIR} ] ; then
		mkdir -p ${ZSH_CACHE_DIR}
	fi
	ZSH_THEME="candy"
	DISABLE_UPDATE_PROMPT=true
	DISABLE_AUTO_UPDATE=true
	plugins=(git)
	source ${ZSH}/oh-my-zsh.sh

# If not, configuration of standard zsh prompt
else
	autoload -U compinit
	compinit
	setopt correctall
	setopt AUTOCD
	autoload -U promptinit
	promptinit
	PS1='%n%# '
	prompt bart
fi
