# PROFIL Kimengumi
# PARTIE SPECIFIQUE A ZSH

if [ ! -e ${HOME}/.zshrc ] ; then
	touch ${HOME}/.zshrc
fi

# ssh-agent (clefs ssh)
# on vérifie si un ssh-agent existe deja pour le user courant 
export SSH_AGENT_PID="`pgrep -u ${USERNAME} ssh-agent | head -n1`"
if [ "x${SSH_AGENT_PID}" != "x" ] ; then
        # on retrouve le socket d'apres le PID
	if [ `ls /tmp/ssh-*/agent.*.${SSH_AGENT_PID} >/dev/null 2>&1` ] ; then
        	for SOCK in `ls --color=never /tmp/ssh-*/agent.*.${SSH_AGENT_PID}` ; do
                	export SSH_AUTH_SOCK="`cat ${SOCK}`"
        	done
	fi
else
        # demarrage ssh-agent
        eval `ssh-agent` >/dev/null
        # fichier permmetant de retrouver le socket d'apres le PID pour la prochaine connexion
        echo ${SSH_AUTH_SOCK} > ${SSH_AUTH_SOCK}.${SSH_AGENT_PID}
fi

# historique
export HISTSIZE=2000
export HISTFILE="${HOME}/.zshist_${USERNAME}_${SUDO_USER}"
export SAVEHIST=${HISTSIZE}
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt extendedglob

# If a local Oh My Zsh is detected, we use it
if [ -e $HOME/.oh-my-zsh/oh-my-zsh.sh ] ; then
	
	# No default configuration in this case, all have to be done in the local user ~/.zshrc

elif [ -e $HOME/.oh-my-zsh/oh-my-zsh.sh ] ; then

	#Basic Oh My Zsh configuration
	export ZSH=$HOME/.oh-my-zsh
	ZSH_THEME="candy"
else
	# standard zsh prompt
	autoload -U compinit
	compinit
	setopt correctall
	zstyle ':completion:*:descriptions' format '%U%B%d%b%u'
	zstyle ':completion:*:warnings' format "%BPas d'autocompletion trouvée dans %d%b"
	zstyle ':completion::complete:*' use-cache 1
	setopt AUTOCD
	autoload -U promptinit
	promptinit
	PS1='%n%# '
	prompt bart
fi
