#!/bin/bash

if [ "x$1" != "x" ]
then
	USER=$1
else
	echo 'nom du compte à créer :'
	read USER
fi

PASS=`/etc/kimengumi/scripts/genpass`

echo "creation du compte : ${USER}"
echo 'mot de passe généré : '${PASS}

for LOCALHOST in "127.0.0.1" "::1" "localhost" ; do
	mysql -e "CREATE USER '${USER}'@'${LOCALHOST}' IDENTIFIED BY '${PASS}'"
	mysql -e "GRANT USAGE ON * . * TO '${USER}'@'${LOCALHOST}' IDENTIFIED BY '${PASS}' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0"
	mysql -e "GRANT ALL PRIVILEGES ON \`${USER}\_%\` . * TO '${USER}'@'${LOCALHOST}'"
done

echo "Fin de création du compte"
