#!/bin/sh

if [ "x$1" = "x" ] || [ "x$2" = "x" ]
then
	echo
	echo	DIFF Recusif evitant les fichiers svn
	echo
        echo "Utilisation: diff_recursif [rep-source] [rep-destination]"
	exit 1;
fi

if [ -e /usr/bin/colordiff ]
then
	DIFF=/usr/bin/colordiff
else
	DIFF=/usr/bin/diff
fi

for fic in `cd $1 && find . -type f | grep -v .svn | egrep ".php|.tpl|.phtml|.xml|.zcml|.py"`
do
	echo "#### $fic" 
	${DIFF} $1/$fic $2/$fic
done



