#!/bin/sh
cd /tmp

USER=`whoami`
VERROU="/tmp/${USER}_magecron_verrou"
LASTEX="/home/${USER}/magecron.lastexec"

if [ ! -f /home/${USER}/magecron.conf ]
then
	echo 'Pas de fichier de config'
	exit
fi

. /home/${USER}/magecron.conf

if [ -f ${VERROU} ]
then 
	#echo "batch precedent encore en cours"
	exit
else
	date > ${VERROU}
	date > ${LASTEX}
	for FIC in ${LISTE}
	do
		(/usr/bin/php -f /home/${USER}/www/${FIC} 2>&1|tee -a ${LASTEX}) || (echo "echeque de ${FIC}"|tee -a ${LASTEX})
	done
	rm ${VERROU} >/dev/null 2>&1
	date >> ${LASTEX}
fi
